[package]
name = "tauri-updater"
version = "0.2.0"
authors = ["Lucas Fernandes Gonçalves Nogueira <lucas@quasar.dev>", "Daniel Thompson-Yvetot <denjell@sfosc.org>", "Tensor Programming <tensordeveloper@gmail.com>"]
license = "MIT"
homepage = "https://tauri-apps.org"
repository = "https://github.com/tauri-apps/tauri"
description = "Updater for Tauri"
edition = "2018"
exclude = ["test/fixture/**"]

[dependencies]
reqwest = "0.10"
hyper-old-types = "0.11.0"
pbr = "1"
serde_json = "1.0.44"
serde = "1.0"
zip = "0.5.3"
sysinfo = "0.10"
tempdir = "0.3"

tauri-api = { version = "0.3", path = "../tauri-api" }
